### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-2-evaluacion-intermedia-jemrosas#1]
Hola @jemrosas, tu ejercicio no tiene mala pinta pero hay un error al arrancar la página. ¿Quieres terminar el ejercicio y luego te lo corrijo?

**Comment by jemrosas** [comment]
Buenas, Miguel!
Si lo permites sí, lo subí así por falta de tiempo. Te aviso en cuánto esté
funcional.

Un saludo!
